name: prodomino
channels:
  - pytorch
  - nvidia
  - conda-forge


dependencies:
  - python=3.10
  - pip=23.3.1
  - pytorch=2.1.0
  - pytorch-cuda=12.1
  - lightning=2.3.0
  - seaborn=0.13.1
  - matplotlib=3.8.1
  - biopython=1.81
  - numpy=1.26
  - py3Dmol=2.1.0
  - torchmetrics=1.4.0
  - notebook=7.0.6

  - pip:
      - fair-esm==2.0.0
      - fairscale==0.4.13
      - fsspec==2024.3.0
